name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-cask:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tap checks
        shell: bash
        run: ./run-tests.sh
